### ISSUE TITLE
Color codes not clearing

### ISSUE THREAD

**Issue by dogweather** [fnando/minitest-utils#4]
Here's what I'm seeing:

![screenshot 2015-05-22 00 20 41](https://cloud.githubusercontent.com/assets/150670/7765903/753f6aa0-0018-11e5-9bf0-dddddfb611ca.png)

I can reproduce it in a fresh Rails app:

``` bash
$ rails new minitest-utils-test
$ cd minitest-utils-test/
$ rails g scaffold post title
$ echo 'gem "minitest-utils"' >> Gemfile
$ bundle
$ rake db:migrate
$ rake
```

![screenshot 2015-05-22 00 30 54](https://cloud.githubusercontent.com/assets/150670/7766034/e0a760a8-0019-11e5-9307-600aa6690c03.png)

**Comment by fnando** [comment]
Hey, thanks for this! I didn't see and fix that in a previous release. I also just released a fix for non-colored output. :)

**Comment by dogweather** [comment]
Sure, you can see I submitted a PR for it, but if you've fixed it, then that's cool https://github.com/fnando/minitest-utils/pull/5
